export const materiData = {
  'Matematika Wajib': [
    'Bilangan - Macam-macam bilangan serta sifatnya',
    'Bilangan - Operasi bilangan (komutatif, asosiatif, distributif)',
    'Aljabar - Sistem persamaan linear banyak variabel',
    'Aljabar - Sistem pertidaksamaan linear multivariabel',
    'Aljabar - Program linear',
    'Aljabar - Barisan dan deret aritmetika & deret geometri',
    'Aljabar - Domain, kodomain, range, invers fungsi, fungsi komposisi, linear, kuadrat',
    'Geometri - Hubungan sudut, garis, dan bidang',
    'Geometri - Kesebangunan, kekongruenan, dan Teorema Pythagoras',
    'Geometri - Transformasi Geometri (Translasi, refleksi, rotasi, dilatasi)',
    'Pengukuran - Keliling & luas bangun datar',
    'Pengukuran - Volume & luas permukaan bangun ruang',
    'Pengukuran - Jarak antar dua objek geometri',
    'Data & Peluang - Penyajian data (diagram batang, garis, lingkaran, grafik, tabel)',
    'Data & Peluang - Ukuran pemusatan & penyebaran data tunggal dan kelompok',
    'Data & Peluang - Aturan peluang',
    'Trigonometri - Perbandingan sinus, cosinus, tangen, cotangen, sekan, dan cosekan',
  ],
  'Bahasa Indonesia Wajib': [
    'Pemahaman Tekstual - Mengidentifikasi informasi dalam teks akademik',
    'Pemahaman Tekstual - Kalimat tanggapan, respons, dan kritik sesuai norma',
    'Pemahaman Tekstual - Kalimat pengajuan usulan dan pemecahan masalah',
    'Pemahaman Tekstual - Mengidentifikasi karakter, peristiwa, latar pada sastra',
    'Evaluasi & Apresiasi - Membandingkan nilai-nilai dalam karya sastra',
    'Evaluasi & Apresiasi - Mengungkapkan kembali isi sastra Melayu Klasik',
    'Evaluasi & Apresiasi - Mengubah informasi dari tabel/grafik menjadi uraian',
    'Evaluasi & Apresiasi - Ketepatan penggunaan bahasa, kiasan, dan citraan',
    'Evaluasi & Apresiasi - Ketepatan penggunaan afiks, frasa, klausa, kalimat',
    'Evaluasi & Apresiasi - Koherensi dan kohesi dalam teks ilmiah',
  ],
  'Bahasa Inggris Wajib': [
    'Pemahaman Tekstual - Menemukan informasi penting & mengklasifikasi objek',
    'Pemahaman Tekstual - Menyusun poin utama & merangkum isi teks',
    'Pemahaman Tekstual - Menggabungkan informasi dari sumber lain',
    'Pemahaman Inferensial - Menentukan fakta tambahan & menyimpulkan pesan moral',
    'Pemahaman Inferensial - Memperkirakan isi selanjutnya & membandingkan persamaan',
    'Pemahaman Inferensial - Menafsirkan sebab-akibat & menyimpulkan sifat tokoh',
    'Pemahaman Inferensial - Memprediksi akhir cerita',
    'Evaluasi & Apresiasi - Menganalisis peristiwa nyata & menilai opini penulis',
    'Evaluasi & Apresiasi - Mengecek kelengkapan & keakuratan informasi',
    'Evaluasi & Apresiasi - Menentukan bagian teks sesuai & menanggapi bacaan',
    'Jenis Teks - Descriptive, Recount, Narrative, Procedure, Analytical Exposition',
  ],
  'Matematika Lanjut': [
    'Matriks - Operasi matriks dasar dan bilangan real',
    'Matriks - Determinan matriks (ukuran 2x2 dan 3x3)',
    'Matriks - Invers matriks (ukuran 2x2 dan 3x3)',
    'Polinomial - Operasi aljabar polinomial (orde maksimum 4)',
    'Polinomial - Pemfaktoran polinomial dan pencarian akar',
    'Polinomial - Teorema sisa dan suku sisa pembagian',
    'Fungsi - Domain, kodomain, dan daerah hasil (range) fungsi lanjut',
    'Fungsi - Grafik fungsi polinom (maksimum orde 4) dan rasional',
    'Fungsi - Grafik fungsi akar dan mutlak',
    'Fungsi - Grafik fungsi eksponensial (bilangan pokok asli) dan logaritma',
    'Fungsi - Grafik dan periode fungsi trigonometri lanjut',
    'Vektor - Komponen vektor pada bidang (2D) dan ruang (3D)',
    'Vektor - Panjang (magnitudo) dan arah vektor',
    'Vektor - Operasi vektor (penjumlahan, pengurangan, perkalian skalar/titik)',
    'Lingkaran - Persamaan lingkaran standar dan umum',
    'Lingkaran - Persamaan garis singgung lingkaran',
    'Lingkaran - Luas dan keliling daerah atau juring bagian lingkaran',
    'Transformasi Geometri - Translasi dan refleksi objek geometris (titik, garis, bangun)',
    'Transformasi Geometri - Rotasi dan dilatasi pada pusat (0,0) atau (a,b)',
    'Transformasi Geometri - Komposisi transformasi menggunakan perkalian matriks',
    'Kalkulus & Limit - Limit fungsi aljabar (non-L\'Hopital / metode faktorisasi)',
    'Kalkulus & Limit - Limit fungsi trigonometri dasar dan manipulasi identitas',
  ],
  'PKK': [
    'Kegiatan Produksi - Desain & Prosedur Produk',
    'Kegiatan Produksi - Evaluasi Desain Kemasan & Label',
    'Kegiatan Produksi - Pengembangan Prototipe',
    'Kegiatan Produksi - Perencanaan & Biaya',
    'Kegiatan Produksi - Proses Produksi',
    'Kegiatan Produksi - Pengemasan Produk',
    'Kegiatan Produksi - Quality Assurance (QA)',
    'Kegiatan Produksi - Evaluasi Strategi & Pemasaran',
    'Kegiatan Produksi - Distribusi Produk',
    'Pengelolaan Usaha - Menentukan Peluang Usaha',
    'Pengelolaan Usaha - Analisis Proposal Usaha',
    'Pengelolaan Usaha - Analisis Laporan Keuangan',
    'Pengelolaan Usaha - Evaluasi Hak Kekayaan Intelektual',
  ],
  'Fisika': [
    'Kinematika - Besaran Satuan dan Vektor',
    'Kinematika - Pengukuran Alat dan Angka Penting',
    'Kinematika - Jarak Perpindahan Kecepatan Kelajuan',
    'Kinematika - GLB dan GLBB',
    'Kinematika - Gerak Parabola dan Gerak Melingkar BB',
    'Dinamika - Konsep Gaya dan Jenis Gaya',
    'Dinamika - Hukum Newton 1 2 3 dan Aplikasinya',
    'Dinamika - Momentum Impuls dan Kekekalan Momentum',
    'Dinamika - Momen Gaya dan Momen Inersia',
    'Dinamika - Hukum Newton tentang Rotasi',
    'Fluida - Fluida Statis Tekanan Pascal Archimedes',
    'Fluida - Fluida Dinamis Hukum Kontinuitas Bernoulli',
    'Gelombang - Gelombang Bunyi Sumber Intensitas',
    'Gelombang - Optik Geometri Cermin Lensa Alat Optik',
    'Gelombang - Sifat Cahaya dan Gelombang Elektromagnet',
    'Kalor - Kalor Perubahan Suhu dan Wujud Zat',
    'Kalor - Pemuaian Perpindahan Kalor Pencampuran Zat',
    'Kalor - Pemanasan Global Efek Rumah Kaca',
    'Kalor - Hukum-hukum Persamaan Gas Ideal',
    'Kalor - 4 Proses Termodinamika dan Mesin Kalor',
    'Fisika Listrik - Listrik Statis Muatan Medan Potensial',
    'Fisika Listrik - Listrik Dinamis Hukum Ohm dan Kirchhoff',
    'Fisika Listrik - Rangkaian Seri Paralel Campuran',
    'Fisika Listrik - Menghitung Daya Listrik',
  ],
  'Kimia': [
    'Atom & Ikatan - Bagian Atom dan Elektron Valensi',
    'Atom & Ikatan - Sistem Periodik Unsur',
    'Atom & Ikatan - Ikatan Ion Kovalen Koordinasi',
    'Atom & Ikatan - Ikatan Logam Gaya Antarmolekul',
    'Stoikiometri - Konsep Mol Perbandingan Tetap Berganda',
    'Stoikiometri - Hukum Avogadro Gas Kekekalan Massa',
    'Stoikiometri - Massa Molar Rumus Empiris Rumus Molekul',
    'Stoikiometri - Kadar Penyetaraan Reaksi Pembatas Rendemen',
    'Kimia Organik - Hidrokarbon Alkana Alkena Alkuna',
    'Kimia Analitik - Kelarutan Konsentrasi Daya Hantar Listrik',
    'Kimia Analitik - Asam Basa dan Garam',
    'Kimia Analitik - Larutan Elektrolit-Non Elektrolit & Sifat Koligatif',
    'Kimia Analitik - Hidrolisis Garam',
    'Kimia Analitik - Larutan Penyangga',
    'Kimia Analitik - pH Larutan Asam Basa',
    'Kimia Analitik - Kesetimbangan Kimia',
    'Kimia Fisik - Reaksi Redoks dan Sel Elektrokimia',
    'Kimia Fisik - Termokimia',
    'Kimia Fisik - Laju Reaksi',
  ],
  'Biologi': [
    'Keanekaragaman - Konsep Keanekaragaman Hayati',
    'Keanekaragaman - Struktur Bakteri dan Peranannya',
    'Keanekaragaman - Ekosistem Interaksi Antarkomponen',
    'Sel - Sel dan Metabolisme Sel',
    'Sel - Enzim dan Cara Kerjanya',
    'Proses - Sistem Sirkulasi',
    'Proses - Sistem Respirasi',
    'Proses - Sistem Ekskresi',
    'Proses - Sistem Imun',
    'Proses - Sistem Koordinasi (Saraf dan Hormon)',
    'Proses - Sistem Reproduksi Pria',
    'Proses - Sistem Reproduksi Wanita',
    'Keterampilan - Merancang Penyelidikan Ilmiah',
    'Keterampilan - Mengolah Data (Memproses dan Menganalisis)',
    'Keterampilan - Menyimpulkan Hasil Penyelidikan',
  ],
  'PPKN': [
    'Pancasila - Makna 5 Sila',
    'Pancasila - Sejarah Perumusan Dasar Negara',
    'Pancasila - Ideologi dan Identitas Nasional',
    'Pancasila - Pelaksanaan HAM',
    'Pancasila - Demokrasi Pancasila',
    'Pancasila - Permasalahan dan Solusi Penerapan',
    'UUD 1945 - Perilaku Taat Hukum',
    'UUD 1945 - Sejarah dan Perkembangan',
    'UUD 1945 - Kewenangan Lembaga Negara',
    'UUD 1945 - Hubungan Pusat dan Daerah',
    'UUD 1945 - Demokrasi Hak Kewajiban WN',
    'Bhinneka Tunggal Ika - Kebersamaan dan Keberagaman',
    'Bhinneka Tunggal Ika - Prinsip Gotong Royong',
    'Bhinneka Tunggal Ika - Potensi Ancaman',
    'NKRI - Perilaku Sesuai Hak-Kewajiban',
    'NKRI - Peran Indonesia pada Perdamaian Dunia',
    'NKRI - Sistem Pertahanan dan Keamanan',
    'NKRI - Praktek Demokrasi',
    'NKRI - Bentuk Negara dan Pemerintahan di Dunia',
  ],
  'Geografi': [
    'Wilayah & Lingkungan - Karakteristik Fisik dan Sosial',
    'Wilayah & Lingkungan - Dinamika Kependudukan',
    'Wilayah & Lingkungan - Keterkaitan Wilayah Fisik Sosial',
    'Wilayah & Lingkungan - Penelitian Geografi',
    'Proses Perubahan - Indikator Keberhasilan Pembangunan',
    'Proses Perubahan - Faktor Dinamika Kependudukan',
    'Proses Perubahan - Konsep Perubahan Lingkungan Fisik',
    'Proses Perubahan - Proses Alam',
    'Proses Perubahan - Peran Manusia',
    'Proses Perubahan - Persebaran Bioma',
    'Interaksi Fisik Alam-Manusia - Posisi Geografis Indonesia',
    'Interaksi Fisik Alam-Manusia - Pengaruh Posisi',
    'Interaksi Fisik Alam-Manusia - Pemanfaatan SDA Sesuai Wilayah',
    'Interaksi Fisik Alam-Manusia - Pengelolaan SDA Berkelanjutan',
    'Mitigasi Bencana - Resiko dan Faktor Penyebab',
    'Mitigasi Bencana - Adaptasi Masyarakat',
    'Mitigasi Bencana - Pengurangan Resiko Bencana',
    'Fenomena Geografi - Penggunaan Peta dan SIG',
    'Fenomena Geografi - Fenomena Geosfer dari Peta/Citra',
  ],
  'Sosiologi': [
    'Ilmu Sosiologi - Pengertian dan Perkembangan',
    'Ilmu Sosiologi - Manfaat Ilmu Pengetahuan',
    'Hubungan & Gejala - Konsep dan Bentuk Hubungan Sosial',
    'Hubungan & Gejala - Lembaga Sosial',
    'Hubungan & Gejala - Ragam Gejala Sosial',
    'Hubungan & Gejala - Dinamika Multikultural',
    'Penelitian - Langkah dan Metode Penelitian Sosial',
    'Kelompok & Konflik - Kelompok Sosial',
    'Kelompok & Konflik - Dinamika Kelompok',
    'Kelompok & Konflik - Faktor Ketidaksetaraan',
    'Kelompok & Konflik - Mewujudkan Kesetaraan',
    'Kelompok & Konflik - Konflik Sosial dan Penanganan',
    'Perubahan Sosial & Globalisasi - Bentuk Perubahan',
    'Perubahan Sosial & Globalisasi - Dampak Perubahan',
    'Perubahan Sosial & Globalisasi - Globalisasi dan Dampaknya',
    'Perubahan Sosial & Globalisasi - Fenomena Globalisasi',
  ],
  'Ekonomi': [
    'Konsep Dasar - Pengertian Ilmu Ekonomi',
    'Konsep Dasar - Konsep Dasar',
    'Konsep Dasar - Permintaan Penawaran Harga',
    'Konsep Dasar - Pendapatan Nasional',
    'Konsep Dasar - Pertumbuhan-Pembangunan',
    'Mikro & Makro - Ketenagakerjaan',
    'Mikro & Makro - Indeks Harga dan Inflasi',
    'Mikro & Makro - Bank Sentral Kebijakan Moneter',
    'Mikro & Makro - Perpajakan Kebijakan Fiskal',
    'Mikro & Makro - Badan Usaha',
    'Internasional & Akuntansi - Kerjasama Internasional',
    'Internasional & Akuntansi - Perdagangan Internasional',
    'Internasional & Akuntansi - Persamaan Dasar Akuntansi',
    'Internasional & Akuntansi - Laporan Keuangan',
  ],
  'Sejarah': [
    'Pengantar - Konsep Perubahan/Keberlanjutan/Sebab-Akibat',
    'Pengantar - Keterkaitan Masa Kini',
    'Pengantar - Sumber Sejarah',
    'Hindu/Buddha/Islam - Teori Masuknya',
    'Hindu/Buddha/Islam - Kehidupan Politik/Ekonomi',
    'Hindu/Buddha/Islam - Peninggalan Budaya',
    'Hindu/Buddha/Islam - Perubahan Pasca Islam',
    'Eropa & Pergerakan - Motivasi Kedatangan Eropa',
    'Eropa & Pergerakan - Pendekatan Diakronik/Sinkronik',
    'Eropa & Pergerakan - Kebijakan Kolonialisme',
    'Eropa & Pergerakan - Perlawanan',
    'Eropa & Pergerakan - Politik Etis',
    'Eropa & Pergerakan - Semangat Tokoh Pergerakan',
    'Eropa & Pergerakan - Runtuhnya Belanda',
    'Eropa & Pergerakan - Masa Pendudukan Jepang',
    'Eropa & Pergerakan - Peristiwa Sekitar Proklamasi',
    'Pasca Kemerdekaan - Pembentukan Negara',
    'Pasca Kemerdekaan - Diplomasi Mempertahankan Kemerdekaan',
    'Pasca Kemerdekaan - Demokrasi Liberal',
    'Pasca Kemerdekaan - Demokrasi Terpimpin',
    'Pasca Kemerdekaan - Transisi Orba',
    'Pasca Kemerdekaan - Kebijakan Orba',
    'Pasca Kemerdekaan - Lahir Reformasi',
    'Pasca Kemerdekaan - Dampak Kebijakan Reformasi',
  ],
};

export const WAJIB_SUBJECTS = ['Matematika Wajib', 'Bahasa Indonesia Wajib', 'Bahasa Inggris Wajib'];
export const ALL_PILIHAN_SUBJECTS = ['Matematika Lanjut', 'PKK', 'Fisika', 'Kimia', 'Biologi', 'PPKN', 'Geografi', 'Sosiologi', 'Ekonomi', 'Sejarah'];
