export const materiData = {
  'Matematika Wajib': [
    'Pertidaksamaan Linear',
    'Sistem Persamaan Linear',
    'Persamaan Garis Lurus',
    'Persamaan Kuadrat',
    'Fungsi Kuadrat',
    'Trigonometri',
    'Relasi dan Fungsi',
    'Fungsi Komposisi dan Invers',
    'Eksponen',
    'Logaritma',
    'Logika Matematika',
    'Induksi Matematika',
    'Pertidaksamaan Linear Dua Variabel',
    'Program Linear',
    'Matriks Dasar dan Operasi Matriks',
    'Barisan dan Deret',
    'Limit Fungsi Aljabar',
    'Turunan Fungsi Aljabar',
    'Integral Tak Tentu',
    'Integral Tentu',
    'Statistik Inferensial',
  ],
  'Bahasa Indonesia': [
    'Laporan Hasil Observasi',
    'Teks Eksposisi',
    'Teks Anekdot',
    'Hikayat',
    'Teks Negosiasi',
    'Debat',
    'Biografi',
    'Puisi',
    'Teks Prosedur',
    'Teks Eksplanasi',
    'Teks Cerpen',
    'Karya Tulis Ilmiah',
    'Drama',
    'Resensi',
    'Surat Lamaran Kerja',
    'Cerita Sejarah',
    'Editorial',
    'Novel',
    'Esai',
    'Artikel',
  ],
  'Bahasa Inggris': [
    'Present Perfect Tense',
    'Recount Text',
    'Simple Future Tense',
    'Past Continuous Tense',
    'Narrative Text',
    'Present Continuous Tense',
    'Family Member',
    'Simple Present Tense',
    'Preference',
    'Simple Past Tense',
    'Announcement Text',
    'Adverb',
    'Pronoun',
    'Descriptive Text',
    'Starting and Ending Conversation',
    'Congratulation and Complimenting Someone',
    'Speech',
    'Passive Voice',
    'Asking dan Giving Opinion',
    'Future Perfect Tense',
    'Analytical Exposition',
    'Formal Letter',
    'Review Text',
    'Procedure Text',
    'Caption Text dan Visual Information',
    'News Item',
    'Job Application Letter',
    'Discussion Text',
    'Offering Help and Making Request',
    'Reported Speech',
  ],
  'Matematika Lanjut': [
    'Matriks - Ordo dan Jenis Matriks',
    'Matriks - Determinan Adjoin dan Invers',
    'Matriks - Operasi Matriks',
    'Suku Banyak - Operasi Polinomial & Pembagian',
    'Suku Banyak - Pemfaktoran & Suku Sisa',
    'Fungsi Lanjut - Domain dan Range',
    'Fungsi Lanjut - Grafik Polinomial',
    'Fungsi Lanjut - Grafik Rasional',
    'Fungsi Lanjut - Grafik Akar Eksponen Logaritma',
    'Fungsi Lanjut - Grafik Fungsi Mutlak',
    'Fungsi Lanjut - Grafik Fungsi Trigonometri',
    'Vektor - Dasar Arah dan Panjang',
    'Vektor - Bidang dan Ruang',
    'Vektor - Operasi Vektor',
    'Lingkaran - Persamaan & Garis Singgung',
    'Lingkaran - Luas dan Keliling',
    'Transformasi Geometri - Matriks Transformasi',
    'Transformasi Geometri - Titik Garis & Bangun Datar',
    'Limit Fungsi - Konsep Dasar',
    'Limit Fungsi - Sifat Limit Aljabar',
    'Limit Fungsi - Limit Trigonometri',
    'Limit Fungsi - Limit Mendekati Tak Hingga',
  ],
  'PKK': [
    'Kegiatan Produksi - Desain & Prosedur Produk',
    'Kegiatan Produksi - Evaluasi Desain Kemasan & Label',
    'Kegiatan Produksi - Pengembangan Prototipe',
    'Kegiatan Produksi - Perencanaan & Biaya',
    'Kegiatan Produksi - Proses Produksi',
    'Kegiatan Produksi - Pengemasan Produk',
    'Kegiatan Produksi - Quality Assurance (QA)',
    'Kegiatan Produksi - Evaluasi Strategi & Pemasaran',
    'Kegiatan Produksi - Distribusi Produk',
    'Pengelolaan Usaha - Menentukan Peluang Usaha',
    'Pengelolaan Usaha - Analisis Proposal Usaha',
    'Pengelolaan Usaha - Analisis Laporan Keuangan',
    'Pengelolaan Usaha - Evaluasi Hak Kekayaan Intelektual',
  ],
  'Fisika': [
    'Kinematika - Besaran Satuan dan Vektor',
    'Kinematika - Pengukuran Alat dan Angka Penting',
    'Kinematika - Jarak Perpindahan Kecepatan Kelajuan',
    'Kinematika - GLB dan GLBB',
    'Kinematika - Gerak Parabola dan Gerak Melingkar BB',
    'Dinamika - Konsep Gaya dan Jenis Gaya',
    'Dinamika - Hukum Newton 1 2 3 dan Aplikasinya',
    'Dinamika - Momentum Impuls dan Kekekalan Momentum',
    'Dinamika - Momen Gaya dan Momen Inersia',
    'Dinamika - Hukum Newton tentang Rotasi',
    'Fluida - Fluida Statis Tekanan Pascal Archimedes',
    'Fluida - Fluida Dinamis Hukum Kontinuitas Bernoulli',
    'Gelombang - Gelombang Bunyi Sumber Intensitas',
    'Gelombang - Optik Geometri Cermin Lensa Alat Optik',
    'Gelombang - Sifat Cahaya dan Gelombang Elektromagnet',
    'Kalor - Kalor Perubahan Suhu dan Wujud Zat',
    'Kalor - Pemuaian Perpindahan Kalor Pencampuran Zat',
    'Kalor - Pemanasan Global Efek Rumah Kaca',
    'Kalor - Hukum-hukum Persamaan Gas Ideal',
    'Kalor - 4 Proses Termodinamika dan Mesin Kalor',
    'Fisika Listrik - Listrik Statis Muatan Medan Potensial',
    'Fisika Listrik - Listrik Dinamis Hukum Ohm dan Kirchhoff',
    'Fisika Listrik - Rangkaian Seri Paralel Campuran',
    'Fisika Listrik - Menghitung Daya Listrik',
  ],
  'Kimia': [
    'Atom & Ikatan - Bagian Atom dan Elektron Valensi',
    'Atom & Ikatan - Sistem Periodik Unsur',
    'Atom & Ikatan - Ikatan Ion Kovalen Koordinasi',
    'Atom & Ikatan - Ikatan Logam Gaya Antarmolekul',
    'Stoikiometri - Konsep Mol Perbandingan Tetap Berganda',
    'Stoikiometri - Hukum Avogadro Gas Kekekalan Massa',
    'Stoikiometri - Massa Molar Rumus Empiris Rumus Molekul',
    'Stoikiometri - Kadar Penyetaraan Reaksi Pembatas Rendemen',
    'Kimia Organik - Hidrokarbon Alkana Alkena Alkuna',
    'Kimia Analitik - Kelarutan Konsentrasi Daya Hantar Listrik',
    'Kimia Analitik - Asam Basa dan Garam',
    'Kimia Analitik - Larutan Elektrolit-Non Elektrolit & Sifat Koligatif',
    'Kimia Analitik - Hidrolisis Garam',
    'Kimia Analitik - Larutan Penyangga',
    'Kimia Analitik - pH Larutan Asam Basa',
    'Kimia Analitik - Kesetimbangan Kimia',
    'Kimia Fisik - Reaksi Redoks dan Sel Elektrokimia',
    'Kimia Fisik - Termokimia',
    'Kimia Fisik - Laju Reaksi',
  ],
  'Biologi': [
    'Keanekaragaman - Konsep Keanekaragaman Hayati',
    'Keanekaragaman - Struktur Bakteri dan Peranannya',
    'Keanekaragaman - Ekosistem Interaksi Antarkomponen',
    'Sel - Sel dan Metabolisme Sel',
    'Sel - Enzim dan Cara Kerjanya',
    'Proses - Sistem Sirkulasi',
    'Proses - Sistem Respirasi',
    'Proses - Sistem Ekskresi',
    'Proses - Sistem Imun',
    'Proses - Sistem Koordinasi (Saraf dan Hormon)',
    'Proses - Sistem Reproduksi Pria',
    'Proses - Sistem Reproduksi Wanita',
    'Keterampilan - Merancang Penyelidikan Ilmiah',
    'Keterampilan - Mengolah Data (Memproses dan Menganalisis)',
    'Keterampilan - Menyimpulkan Hasil Penyelidikan',
  ],
  'Bahasa Inggris Lanjut': [
    'Tekstual - Mengidentifikasi Gagasan Utama',
    'Tekstual - Mengidentifikasi Informasi Penting yang Eksplisit',
    'Tekstual - Mengelompokkan Argumen/Fakta/Pendapat',
    'Tekstual - Membuat Struktur/Kerangka Teks/Bacaan',
    'Tekstual - Menyajikan (Summary) Isi Teks',
    'Tekstual - Menggabungkan Informasi dari Sumber Lain',
    'Inferensial - Detail Pendukung/Fakta Tambahan',
    'Inferensial - Topik Ide Pokok Makna dan Target Pembaca',
    'Inferensial - Tujuan Penulisan Teks dan Pesan Moral Teks',
    'Inferensial - Hubungan Antar Ide Argumen Bukti dalam Teks',
    'Inferensial - Hubungan Sebab Akibat pada Teks',
    'Inferensial - Sudut Pandang Penulis (Author\'s Tone)',
    'Inferensial - Dampak Gagasan dan Argumen pada Teks',
    'Evaluasi - Fakta dan Opini pada Teks',
    'Evaluasi - Kecukupan dan Kelengkapan Informasi',
    'Evaluasi - Kekuatan/Kelogisan Argumen pada Teks',
    'Evaluasi - Memberi Opini/Pendapat tentang Teks',
  ],
  'Bahasa Indonesia Lanjut': [
    'Tekstual - Identifikasi Informasi Teks Akademik',
    'Tekstual - Menyampaikan Tanggapan/Kritik/Respon',
    'Tekstual - Mengajukan Usulan/Perumusan/Pemecahan Masalah',
    'Tekstual - Identifikasi Karakter/Peristiwa/Latar pada Sastra',
    'Inferensial - Nilai Budaya/Sosial/Moral/Religi/Pendidikan pada Sastra',
    'Inferensial - Mengungkapkan Isi Sastra Melayu Klasik',
    'Inferensial - Mengubah Informasi Tabel/Grafik ke Uraian dan Sebaliknya',
    'Inferensial - Ketepatan Penggunaan Bahasa/Kiasan/Citraan',
    'Inferensial - Penggunaan Afiks/Konstruksi Frasa/Klausa/Kalimat',
    'Inferensial - Kohesi dan Koherensi Teks Ilmiah',
    'Inferensial - Gagasan dan Pandangan (Logika Berpikir)',
    'Evaluasi - Kesesuaian Isi Teks (Sosial/Akademik/Dunia Kerja)',
    'Evaluasi - Gagasan/Tindakan Tokoh Berdasarkan Norma',
    'Evaluasi - Alihwahana Puisi dalam Prosa',
    'Evaluasi - Respon Emosional terhadap Unsur Sastra',
  ],
  'PPKN': [
    'Pancasila - Makna 5 Sila',
    'Pancasila - Sejarah Perumusan Dasar Negara',
    'Pancasila - Ideologi dan Identitas Nasional',
    'Pancasila - Pelaksanaan HAM',
    'Pancasila - Demokrasi Pancasila',
    'Pancasila - Permasalahan dan Solusi Penerapan',
    'UUD 1945 - Perilaku Taat Hukum',
    'UUD 1945 - Sejarah dan Perkembangan',
    'UUD 1945 - Kewenangan Lembaga Negara',
    'UUD 1945 - Hubungan Pusat dan Daerah',
    'UUD 1945 - Demokrasi Hak Kewajiban WN',
    'Bhinneka Tunggal Ika - Kebersamaan dan Keberagaman',
    'Bhinneka Tunggal Ika - Prinsip Gotong Royong',
    'Bhinneka Tunggal Ika - Potensi Ancaman',
    'NKRI - Perilaku Sesuai Hak-Kewajiban',
    'NKRI - Peran Indonesia pada Perdamaian Dunia',
    'NKRI - Sistem Pertahanan dan Keamanan',
    'NKRI - Praktek Demokrasi',
    'NKRI - Bentuk Negara dan Pemerintahan di Dunia',
  ],
  'Geografi': [
    'Wilayah & Lingkungan - Karakteristik Fisik dan Sosial',
    'Wilayah & Lingkungan - Dinamika Kependudukan',
    'Wilayah & Lingkungan - Keterkaitan Wilayah Fisik Sosial',
    'Wilayah & Lingkungan - Penelitian Geografi',
    'Proses Perubahan - Indikator Keberhasilan Pembangunan',
    'Proses Perubahan - Faktor Dinamika Kependudukan',
    'Proses Perubahan - Konsep Perubahan Lingkungan Fisik',
    'Proses Perubahan - Proses Alam',
    'Proses Perubahan - Peran Manusia',
    'Proses Perubahan - Persebaran Bioma',
    'Interaksi Fisik Alam-Manusia - Posisi Geografis Indonesia',
    'Interaksi Fisik Alam-Manusia - Pengaruh Posisi',
    'Interaksi Fisik Alam-Manusia - Pemanfaatan SDA Sesuai Wilayah',
    'Interaksi Fisik Alam-Manusia - Pengelolaan SDA Berkelanjutan',
    'Mitigasi Bencana - Resiko dan Faktor Penyebab',
    'Mitigasi Bencana - Adaptasi Masyarakat',
    'Mitigasi Bencana - Pengurangan Resiko Bencana',
    'Fenomena Geografi - Penggunaan Peta dan SIG',
    'Fenomena Geografi - Fenomena Geosfer dari Peta/Citra',
  ],
  'Sosiologi': [
    'Ilmu Sosiologi - Pengertian dan Perkembangan',
    'Ilmu Sosiologi - Manfaat Ilmu Pengetahuan',
    'Hubungan & Gejala - Konsep dan Bentuk Hubungan Sosial',
    'Hubungan & Gejala - Lembaga Sosial',
    'Hubungan & Gejala - Ragam Gejala Sosial',
    'Hubungan & Gejala - Dinamika Multikultural',
    'Penelitian - Langkah dan Metode Penelitian Sosial',
    'Kelompok & Konflik - Kelompok Sosial',
    'Kelompok & Konflik - Dinamika Kelompok',
    'Kelompok & Konflik - Faktor Ketidaksetaraan',
    'Kelompok & Konflik - Mewujudkan Kesetaraan',
    'Kelompok & Konflik - Konflik Sosial dan Penanganan',
    'Perubahan Sosial & Globalisasi - Bentuk Perubahan',
    'Perubahan Sosial & Globalisasi - Dampak Perubahan',
    'Perubahan Sosial & Globalisasi - Globalisasi dan Dampaknya',
    'Perubahan Sosial & Globalisasi - Fenomena Globalisasi',
  ],
  'Ekonomi': [
    'Konsep Dasar - Pengertian Ilmu Ekonomi',
    'Konsep Dasar - Konsep Dasar',
    'Konsep Dasar - Permintaan Penawaran Harga',
    'Konsep Dasar - Pendapatan Nasional',
    'Konsep Dasar - Pertumbuhan-Pembangunan',
    'Mikro & Makro - Ketenagakerjaan',
    'Mikro & Makro - Indeks Harga dan Inflasi',
    'Mikro & Makro - Bank Sentral Kebijakan Moneter',
    'Mikro & Makro - Perpajakan Kebijakan Fiskal',
    'Mikro & Makro - Badan Usaha',
    'Internasional & Akuntansi - Kerjasama Internasional',
    'Internasional & Akuntansi - Perdagangan Internasional',
    'Internasional & Akuntansi - Persamaan Dasar Akuntansi',
    'Internasional & Akuntansi - Laporan Keuangan',
  ],
  'Sejarah': [
    'Pengantar - Konsep Perubahan/Keberlanjutan/Sebab-Akibat',
    'Pengantar - Keterkaitan Masa Kini',
    'Pengantar - Sumber Sejarah',
    'Hindu/Buddha/Islam - Teori Masuknya',
    'Hindu/Buddha/Islam - Kehidupan Politik/Ekonomi',
    'Hindu/Buddha/Islam - Peninggalan Budaya',
    'Hindu/Buddha/Islam - Perubahan Pasca Islam',
    'Eropa & Pergerakan - Motivasi Kedatangan Eropa',
    'Eropa & Pergerakan - Pendekatan Diakronik/Sinkronik',
    'Eropa & Pergerakan - Kebijakan Kolonialisme',
    'Eropa & Pergerakan - Perlawanan',
    'Eropa & Pergerakan - Politik Etis',
    'Eropa & Pergerakan - Semangat Tokoh Pergerakan',
    'Eropa & Pergerakan - Runtuhnya Belanda',
    'Eropa & Pergerakan - Masa Pendudukan Jepang',
    'Eropa & Pergerakan - Peristiwa Sekitar Proklamasi',
    'Pasca Kemerdekaan - Pembentukan Negara',
    'Pasca Kemerdekaan - Diplomasi Mempertahankan Kemerdekaan',
    'Pasca Kemerdekaan - Demokrasi Liberal',
    'Pasca Kemerdekaan - Demokrasi Terpimpin',
    'Pasca Kemerdekaan - Transisi Orba',
    'Pasca Kemerdekaan - Kebijakan Orba',
    'Pasca Kemerdekaan - Lahir Reformasi',
    'Pasca Kemerdekaan - Dampak Kebijakan Reformasi',
  ],
};

export const WAJIB_SUBJECTS = ['Matematika Wajib', 'Bahasa Indonesia', 'Bahasa Inggris'];
export const ALL_PILIHAN_SUBJECTS = ['Matematika Lanjut', 'PKK', 'Fisika', 'Kimia', 'Biologi', 'Bahasa Inggris Lanjut', 'Bahasa Indonesia Lanjut', 'PPKN', 'Geografi', 'Sosiologi', 'Ekonomi', 'Sejarah'];
